spring:
  profiles: docker
  zipkin:
    baseUrl:  http://zipkin:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/
  instance:
    preferIpAddress: true
